name: latex

on:
  push:
    branches:
      - main
      - development

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          args: -lualatex -shell-escape -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: versioning
        id: versioning
        uses: codacy/git-version@2.5.4
        with:
          release-branch: main
          dev-branch: development
          minor-identifier: 'minor:'
          major-identifier: 'major:'
      - name: release
        id: github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: Release ${{ steps.versioning.outputs.version }}
          prerelease: ${{ github.ref == 'refs/heads/main' && 'false' || 'true' }}
      - name: upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github-release.outputs.upload_url }}
          asset_path: thesis.pdf
          asset_name: thesis.pdf
          asset_content_type: application/pdf